version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2182:2181
    networks:
      - GLhost

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9093:9092
      - 29092:29092
    networks:
      - GLhost
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo-db:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: postgres
      MONGO_INITDB_ROOT_PASSWORD: 20005
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - GLhost

  booking_service:
    container_name: booking_service
    build: .
    depends_on:
      - mongo-db
      - kafka
    ports:
      - "7777:7777"
    networks:
      - GLhost

  redis:
    image: redis:latest
    container_name: redis_booking_service
    ports:
      - "6390:6379"
    networks:
      - GLhost

networks:
  GLhost:
    external: true
    name: car_wash
    driver: bridge

volumes:
  mongo-data:
