name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          echo BOSHLANDIIIIIIIIIIIIIIIIIIIIIIIIIIi
          git clone git@github.com:IsakovDiyorbek/Exam-5.git

          cd Car-Wash-Api-Gateway
          sudo docker compose down
          sudo docker compose up --build
          sudo docker compose down
          sudo docker compose up

          cd ..
          cd Car-Wash-Auht-Service
          sudo docker compose down
          sudo docker compose up --build
          sudo docker compose down
          sudo docker compose up

          cd ..
          cd Car-Wash-Booking-Service
          sudo docker compose down
          sudo docker compose up --build

          sudo docker compose down
          sudo docker compose up 
