name: Hello World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          echo "BOSHLANDIIIIIIIIIIIIIIIIIIIIIIIIIIi"
          if [ ! -d "Car-Wash" ]; then
            git clone git@github.com:IsakovDiyorbek/Car-Wash.git
          fi

          cd Car-Wash || exit

          # Car-Wash-Api-Gateway
          cd Car-Wash-Api-Gateway || exit
          git pull origin main
          sudo docker compose down || echo "Failed to bring down Car-Wash-Api-Gateway"
          sudo docker compose up --build -d || echo "Failed to build Car-Wash-Api-Gateway"

          # Car-Wash-Auth-Service
          cd ../Car-Wash-Auth-Service || exit
          git pull origin main
          sudo docker compose down || echo "Failed to bring down Car-Wash-Auth-Service"
          sudo docker compose up --build -d  || echo "Failed to build Car-Wash-Auth-Service"

          # Car-Wash-Booking-Service
          cd ../Car-Wash-Booking-Service || exit
          git pull origin main
          sudo docker compose down || echo "Failed to bring down Car-Wash-Booking-Service"
          sudo docker compose up --build -d  || echo "Failed to build Car-Wash-Booking-Service"
